"""truth.x — AI Text Detector (RoBERTa) with Grounded Forensic Analysis.

Primary Engine: Hello-SimpleAI/chatgpt-detector-roberta
Architecture: RoBERTa-base Sequence Classification
Verification Layers:
    - Perplexity scoring (HF API — GPT-2)
    - Burstiness analysis (LOCAL)
    - Stylometric analysis (LOCAL)
    - Emotional manipulation detection
"""

from __future__ import annotations

import gc
import math
import os
import re
from collections import Counter
from typing import Any, Dict, List

import numpy as np
import torch
import yaml
from transformers import AutoTokenizer, AutoModelForSequenceClassification

from backend.detectors.base import BaseDetector
from backend.utils.logger import logger

_BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONFIG_PATH = os.path.join(_BACKEND_DIR, "config", "config.yaml")


def _load_config() -> dict:
    with open(CONFIG_PATH, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


# ─── Emotional / Manipulation Markers ────────────────────────────────────

_LOADED_WORDS = {
    "shocking", "outrageous", "devastating", "horrifying", "explosive",
    "bombshell", "terrifying", "alarming", "appalling", "disgusting",
    "scandalous", "unbelievable", "horrific", "catastrophic", "dire",
}

_URGENCY_PATTERNS = [
    r"\b(breaking|urgent|alert|just in|share now|act now|limited time)\b",
    r"!{2,}",
    r"\b(you won'?t believe|they don'?t want you to know)\b",
]

_PROPAGANDA_PATTERNS = [
    r"\b(wake up|open your eyes|sheeple|mainstream media lies)\b",
    r"\b(big pharma|deep state|cover[- ]up|conspiracy)\b",
    r"\b(the truth about|exposed|revealed|hidden)\b",
]


class TextAIDetector(BaseDetector):
    """Detects whether text was generated by an AI model using RoBERTa.
    Strictly enforced grounded inference with no silent fallbacks.
    """

    modality = "text"

    def __init__(self) -> None:
        super().__init__()
        cfg = _load_config()
        text_cfg = cfg.get("text", {})
        
        # Primary Model: RoBERTa-based ChatGPT detector
        self.model_name: str = "Hello-SimpleAI/chatgpt-detector-roberta"
        self.max_length: int = text_cfg.get("max_length", 512)
        self.threshold: float = text_cfg.get("threshold", 0.5)

        # Ensemble weights
        self.weight_primary: float = 0.70
        self.weight_perplexity: float = 0.10
        self.weight_burstiness: float = 0.10
        self.weight_stylometric: float = 0.10
        
        self.tokenizer = None
        self.model = None

        try:
            logger.info("Loading robust text detector '%s' on %s", self.model_name, self.device)
            self.tokenizer = AutoTokenizer.from_pretrained(self.model_name)
            self.model = AutoModelForSequenceClassification.from_pretrained(self.model_name)
            self.model.to(self.device)
            self.model.eval()
            logger.info("Text model loaded successfully ✓")
        except Exception as e:
            logger.error("CRITICAL: Failed to load text model: %s", e)
            self.model = None

    def _run_primary_inference(self, text: str) -> float:
        """Run the primary ChatGPT-RoBERTa classifier with strict length limits."""
        # RoBERTa max_position_embeddings is typically 514 (512 + 2)
        # We must truncate strictly to 512 to avoid "tensor size mismatch" errors
        safe_max_length = 512
        
        inputs = self.tokenizer(
            text, return_tensors="pt", truncation=True,
            max_length=safe_max_length, padding=True,
        )
        inputs = {k: v.to(self.device) for k, v in inputs.items()}
        
        # Guard against unexpected tensor shapes before forward pass
        seq_len = inputs["input_ids"].shape[1]
        if seq_len > 514:
             logger.warning("Truncation failed? seq_len=%d. Force slicing.", seq_len)
             inputs["input_ids"] = inputs["input_ids"][:, :514]
             inputs["attention_mask"] = inputs["attention_mask"][:, :514]

        outputs = self.model(**inputs)
        
        # Labels: 0 -> Human, 1 -> ChatGPT
        probs = torch.softmax(outputs.logits, dim=-1).cpu().tolist()[0]
        return float(probs[1])

    @torch.no_grad()
    def predict(self, text: str) -> Dict[str, Any]:
        """Classify text with grounded neural inference and no silent fallbacks."""
        if not text or not text.strip():
            return self._format_result(
                label="unknown", confidence=0.0, fake_probability=0.0,
                extra={"ai_probability": 0.0, "human_probability": 0.0},
            )

        reasons: List[Dict[str, Any]] = []

        # ── 1. Primary Classification (Grounded Neural Inference) ──
        if self.model is not None and self.tokenizer is not None:
            try:
                primary_ai_prob = self._run_primary_inference(text)
            except Exception as e:
                logger.error("CRITICAL: Primary text neural engine failed: %s", e)
                # Fail honestly: do not fabricate probabilities
                raise RuntimeError(f"Text neural inference failed: {e}. Pipeline aborted.")
        else:
            logger.error("Text detector model or tokenizer missing.")
            raise RuntimeError("Text neural engine offline. Pipeline aborted.")

        # ── 2. Forensic Signal Extraction (Corroborating Evidence) ──
        # These only run if primary inference succeeded
        burstiness = self._analyze_burstiness(text, reasons)
        stylometric = self._analyze_stylometrics(text, reasons)
        perplexity = self._estimate_perplexity(text, reasons)

        # ── 3. Forensic Signal Driven Aggregation ──
        # PHILOSOPHY: If forensic signals are strong, they should anchor the result
        # even if the primary neural engine is neutral or under-sensitive.
        
        forensic_signals = [burstiness, stylometric]
        if perplexity is not None:
            forensic_signals.append(perplexity)
        
        max_forensic = max(forensic_signals)
        
        if max_forensic > 0.75:
            # High-confidence forensic indicators anchor the floor
            # We take the max of primary and the forensic floor
            fake_prob = max(primary_ai_prob, max_forensic * 0.85)
            logger.info("Anomaly Anchor active: max_forensic=%.2f anchoring fake_prob to %.4f", max_forensic, fake_prob)
        else:
            # Normal ensemble weighted approach
            if perplexity is not None:
                fake_prob = (
                    self.weight_primary * primary_ai_prob
                    + self.weight_perplexity * perplexity
                    + self.weight_burstiness * burstiness
                    + self.weight_stylometric * stylometric
                )
            else:
                total = self.weight_primary + self.weight_burstiness + self.weight_stylometric
                fake_prob = (
                    (self.weight_primary / total) * primary_ai_prob
                    + (self.weight_burstiness / total) * burstiness
                    + (self.weight_stylometric / total) * stylometric
                )

        fake_prob = max(0.0, min(1.0, fake_prob))
        human_prob = 1.0 - fake_prob

        label = "ai-generated" if fake_prob >= self.threshold else "human-written"
        confidence = fake_prob if label == "ai-generated" else human_prob

        # Emotional manipulation check
        self._check_manipulation(text, reasons)

        self._cleanup_gpu()

        logger.info("Forensic text analysis complete: label=%s, fake_prob=%.4f", label, fake_prob)

        return self._format_result(
            label=label,
            confidence=confidence,
            fake_probability=fake_prob,
            reasons=reasons,
            extra={
                "ai_probability": round(fake_prob, 4),
                "human_probability": round(human_prob, 4),
                "technical_signals": {
                    "primary_model_score": round(primary_ai_prob, 4),
                    "burstiness_score": round(burstiness, 4),
                    "stylometric_score": round(stylometric, 4),
                    "perplexity_score": round(perplexity, 4) if perplexity is not None else None,
                },
            },
        )

    # ── Internal Analysis Methods ─────────────────────────────────────────

    def _analyze_burstiness(self, text: str, reasons: List) -> float:
        """Measure text burstiness — AI text has unnaturally uniform patterns."""
        sentences = re.split(r'[.!?]+\s+', text)
        sentences = [s.strip() for s in sentences if len(s.strip()) > 5]

        if len(sentences) < 3:
            return 0.3

        lengths = [len(s.split()) for s in sentences]
        mean_len = np.mean(lengths)
        std_len = np.std(lengths)
        cv_length = std_len / max(mean_len, 1)

        uniformity = 1.0 - min(1.0, cv_length)

        if uniformity > 0.7:
            reasons.append(self._make_reason(
                "low_burstiness", "medium",
                "Unnaturally uniform sentence length structure detected.",
                f"Coefficient of variation: {cv_length:.3f}"
            ))

        return uniformity

    def _analyze_stylometrics(self, text: str, reasons: List) -> float:
        """Analyze linguistic style features."""
        words = re.findall(r'\b\w+\b', text.lower())
        if len(words) < 20:
            return 0.3

        unique_words = set(words)
        ttr = len(unique_words) / len(words)
        
        # AI typically falls in the 0.35-0.55 range for TTR
        ai_like_ttr = 1.0 if (0.38 < ttr < 0.52) else 0.2
        
        if ai_like_ttr > 0.8:
            reasons.append(self._make_reason(
                "vocabulary_consistency", "low",
                "Vocabulary richness consistent with neural generator constraints.",
                f"Type-Token Ratio: {ttr:.3f}"
            ))

        return ai_like_ttr

    def _estimate_perplexity(self, text: str, reasons: List) -> float | None:
        """Estimate text predictability (low entropy = likely AI)."""
        entropy = self._char_entropy(text)
        if entropy < 3.8:
            reasons.append(self._make_reason(
                "low_perplexity", "medium",
                "Text exhibits low character-level entropy; highly predictable sequence.",
                f"Entropy: {entropy:.3f} bits/char"
            ))
            return 0.8
        return 0.3

    @staticmethod
    def _char_entropy(text: str) -> float:
        if not text: return 0.0
        freq = Counter(text.lower())
        total = len(text)
        return -sum((count / total) * math.log2(count / total) for count in freq.values())

    def _check_manipulation(self, text: str, reasons: List) -> None:
        lower = text.lower()
        loaded_found = [w for w in _LOADED_WORDS if w in lower]
        if len(loaded_found) >= 2:
            reasons.append(self._make_reason(
                "emotional_manipulation", "medium",
                f"Use of emotionally loaded terms: {', '.join(loaded_found[:3])}"
            ))

        for pattern in _URGENCY_PATTERNS:
            if re.search(pattern, lower):
                reasons.append(self._make_reason("urgency_markers", "medium", "Pressure-oriented urgency patterns detected."))
                break
